version: "3.6"

services:
  leaderboard-api:
    image: "skynetlabs/leaderboard-api"
    container_name: leaderboard-api
    depends_on:
      - "mongo"
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017"
      DEBUG_ENABLED: "false"
      LEADERBOARDAPI_PORT: "4000"
    ports:
      - "4000:4000"
  mongo:
    image: "bitnami/mongodb:4.2"
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
